---

version: '3.5'

services:
#  config:
#    image: tnt-ms-architecture/tnt-ms-config
#    networks:
#      - tnt-ms-network
#    ports:
#      - "8888:8888"
#      
#  eureka:
#    image: tnt-ms-architecture/tnt-ms-eureka
#    hostname: discovery
#    networks:
#      - tnt-ms-network
#    ports:
#      - "8761:8761"
#
#  zuul:
#    image: tnt-ms-architecture/tnt-ms-zuul
#    networks:
#      - tnt-ms-network
#    ports:
#      - "8090:8090"
#      
#  hystrix:
#    image: tnt-ms-architecture/tnt-ms-hystrix
#    networks:
#      - tnt-ms-network
#    ports:
#      - "8030:8030"
#      
#  zipkin:
#    image: tnt-ms-architecture/tnt-ms-zipkin
#    networks:
#      - tnt-ms-network
#    ports:
#      - "9411:9411"
      
  ms-catalog-1:
    image: microservices/tnt-ms-catalog
    networks:
      - tnt-ms-network
    ports:
      - "8050:8081"
      
#  ms-catalog-2:
#    image: tnt-ms-architecture/tnt-ms-catalog
#    networks:
#      - tnt-ms-network
#    ports:
#      - "8051:8081"
#
#  ms-orders-1:
#    image: tnt-ms-architecture/tnt-ms-orders
#    networks:
#      - tnt-ms-network
#    ports:
#      - "8060:8080"
  
  # ELK services
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    container_name: elasticsearch${ELASTIC_VERSION}
    environment:
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    volumes:
      - ./elk-config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - tnt-ms-network
    ports:
      - "9200:9200"

  logstash:
    image: docker.elastic.co/logstash/logstash:${ELASTIC_VERSION}
    container_name: logstash${ELASTIC_VERSION}
    environment:
      - ELASTIC_USER=${ELASTIC_USER}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    volumes:
      - ./elk-config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./elk-config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    networks:
      - tnt-ms-network
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:${ELASTIC_VERSION}
    container_name: kibana${ELASTIC_VERSION}
    environment:
      - ELASTICSEARCH_USERNAME=${ELASTIC_USER}
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
    volumes:
      - ./elk-config/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    networks:
      - tnt-ms-network
    depends_on:
      - elasticsearch

networks:
  tnt-ms-network:
    driver: bridge

