server:
  port: 8083

spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql

  cloud:
    stream:
      bindings:
        output:
          destination: queue.orders.events
          binder: local_rabbit
      binders:
        local_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
                virtual-host: /
                
                
logging:
  level:
    root: INFO

management:
  security:
    enabled: false
  health:
    binders:
       enabled: true

spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS: false

